P12_15html_Task/urls.py
from django.contrib import admin
from django.urls import path,include
import app1,app2,app3

urlpatterns = [
    path('admin/', admin.site.urls),
    path('app1/', include('app1.urls')),
    path('app2/', include('app2.urls')),
    path('app3/', include('app3.urls')),
]

app1/urls.py
from django.urls import path
from app1.views import *

app_name='app1'

urlpatterns=[
    path('table/', table,name='table'),
    path('table1/', table1, name='table1'),
    path('table2/', table2, name='table2'),
    path('table3/', table3, name='table3'),
    path('table4/', table4, name='table4'),
    path('table5/', table5, name='table5'),
    path('home/', home, name='home'),
]

app2/urls.py
from django.urls import path
from app2.views import *
app_name='app2'
urlpatterns=[
    path('login1/', login1, name='login1'),
    path('login2/', login2, name='login2'),
    path('login3/', login3, name='login3'),
    path('card/', card, name='card'),

]

app3/urls.py
from django.urls import path
from app3.views import *
app_name='app3'
urlpatterns=[
    path('animation/', animation, name='animation'),
    path('animation2/', animation2, name='animation2'),
    path('animation3/', animation3, name='animation3'),
]

app1/models.py
from django.db import models

# Create your models here.

app2/models.py
from django.db import models

# Create your models here.

app3/models.py
from django.db import models

# Create your models here.

app1/views.py
from django.shortcuts import render

# Create your views here.
def table(request):
    return render (request, 'table.html')

def table1(request):
    return render(request, 'table1.html')

def table2(request):
    return render(request, 'table2.html')

def table3(request):
    return render(request, 'table3.html')

def table4(request):
    return render(request, 'table4.html')

def table5(request):
    return render(request, 'table5.html')

def home(request):
    return render(request, 'landingpage.html')

app2/views.py
from django.shortcuts import render

# Create your views here.
def login1(request):
    return render(request,'login1.html') 

def login2(request):
    return render(request, 'login2.html')

def login3(request):
    return render(request, 'login3.html')

def card(request):
    return render(request, 'Card.html')

app3/views.py
from django.shortcuts import render

# Create your views here.
def animation(request):
    return render(request, 'animation.html')

def animation2(request):
    return render(request, 'animation2.html')

def animation3(request):
    return render(request, 'annimation3.html')

templates/EX.html
<!DOCTYPE html>
<html>
<head>
    <title>WEB</title>
    <link rel="stylesheet" href="../CSS/CSS/FONT/css/all.css">
    <link rel="shortcut icon" href="../PIC/dog-solid.svg" type="image/x-icon">
    <style>
        *
        {
            margin: 0px;
        }
        body
        {
            background-color: lightskyblue;
        }
        nav
        {
            background-color: burlywood;
            display: flex;
            justify-content: space-between;
            height: 100px;
            align-items: center;
        }
        div ul
        {
            display: flex;
        }
        div ul li
        {
            margin-left: 7px;
            list-style: none;

        }
        #top
        {
            margin-left: 10px;
            letter-spacing: 3px;
            font-family: Impact, Haettenschweiler, 'Arial Narrow Bold', sans-serif;
        }
        #top::first-letter
        {
            background-color: brown;
            border: 2px solid black;
            border-radius: 0px 10px 0px 10px;
            padding: 8px;
            font-size: 25px;
            font-family: Impact, Haettenschweiler, 'Arial Narrow Bold', sans-serif;
        }
        aside
        {
            background-color: rgb(241, 215, 180);
            display: flex;
            justify-content: center;
            height: 800px;
            width: 200px;
        }
        aside ul li
        {
            margin-bottom:40px;
            list-style: none;
            padding: 50px;
        }
        aside ul li a
        {
            text-decoration: none;
            font-size: 20px;
        }
        section
        {
            display: flex;
            justify-content: space-around;
        }
        #text
        {
            width: 10%;
        }
        #aud
        {
            margin: 100px;
        }
        .vid
        {
            margin-left: 400px;
        }
        .vid>video
        {
            height: 500px;
            width:500px;
        }
    </style>
</head>
<body>
    <nav>
        <div id="top">Jspider</div>
            <div>
                <ul>
                    <li>Home</li>
                    <li>Contact</li>
                    <li>About</li>
                    <li>Help</li>
                </ul>
            </div>
    </nav>
    <section>
        <aside>
            <ul>
                <li><a href="">Html</a></li>
                <li><a href="">CSS</a></li>
                <li><a href="">Java</a></li>
                <li><a href="">Python</a></li>
                <li><a href="">SQL</a></li>
            </ul>
        </aside>
    <div id="text"></div>
    <article>
        <h2>About Html</h2>
        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Aliquam impedit commodi ab tempora necessitatibus? Assumenda, autem dolor ipsum earum necessitatibus quaerat optio tempore aperiam enim praesentium, harum totam architecto at?Lorem ipsum dolor sit amet consectetur adipisicing elit. Corporis nobis commodi, ratione quisquam vitae laborum saepe, illo deserunt beatae itaque debitis similique repudiandae soluta ad excepturi non totam, animi nam.
        Suscipit, est? Eos, quos architecto perferendis similique omnis minima rem qui suscipit autem quo nostrum tempore dolor dignissimos ut delectus a illum rerum pariatur nesciunt nihil voluptatem quibusdam aspernatur sapiente!
        Voluptatem,Lorem ipsum dolor sit amet consectetur adipisicing elit. Vel eaque obcaecati commodi recusandae eligendi labore dolores dignissimos exercitationem unde enim, veniam velit facilis reiciendis hic rem porro soluta quaerat odit!
        Fugit omnis et, magni impedit nemo obcaecati corrupti ipsam doloremque rerum architecto mollitia adipisci temporibus molestiae eius dolores amet, necessitatibus voluptas ad? Praesentium, fuga optio commodi numquam sequi nemo aperiam?
        Obcaecati, magnam fugiat. Magnam corporis labore consequatur aperiam. Provident consequatur doloribus reprehenderit perspiciatis aspernatur similique ea optio temporibus incidunt? Iusto pariatur amet odio libero adipisci nostrum, iure nam eum illum? nemo minus asperiores cumque veniam dolorum qui numquam dolores et facere modi pariatur veritatis quaerat recusandae ut at a rerum omnis eveniet consequatur perspiciatis eaque! Consequatur unde non deleniti?
    </article>
    </section>
    <div id="aud">
        <audio controls><source src="../MAY/IMAGE/शोधिसी_मानवा_राउळी_मंदिरी_-_अभंग_आणि_भक्तिगीते___Pahatechi_Bhakti_Geete_Marathi-_Shodhisi_Manava(128k).m4a"></audio>
    </div>
    <div class="vid">
        <video controls><source src=""></video>
    </div>
    <div>
        <iframe width="560" height="315" src="https://www.youtube.com/embed/8sLS2knUa6Y" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe>
    </div>
</body>
</html>

templates/LeapYear.html
<!DOCTYPE html>
<html>
<head>
    <title>Leap Year</title>
    
</head>
<body>
    <h1>Leap Year</h1>
    <script>
        function year()
        {
            let yer =prompt('enter year')
            if ((yer%100==0) && (yer%400==0))
            {
                console.log('The Century year is leap year'+yer);
            }
            else if ((yer%100!=0) && (yer%4==0))
            {
                console.log('The normal year is leap :'+yer);
            }
            else
            {
                console.log('Year is not leap :'+yer);
            }
        }
        year();
    </script>
</body>
</html>

templates/divtag.html
<!DOCTYPE html>
<html>
<head>
    <title>DIV tags</title>
    <style>
        .a,.b,.c,.d,.e
        {
            border:10px solid black;
            margin-bottom: 10px;
            border-radius:10px; 
        }
        .a
        {
            background-color: brown;
            width: 100px;
            height: 100px;
            padding: 10px;
            
        }
        .b
        {
            background-color: black;
            width: 100px;
            margin-left: 100px;
            height: 100px;
        }
        .c
        {
            background-color:red;
            width: 100px;
            margin-left: 200px;
            height: 100px;
        }
        .d
        {
            background-color:blueviolet;
            width: 100px;
            margin-left: 300px;
            height: 100px;
        }
        .e
        {
            background-color: violet;
            width: 100px;
            margin-left: 400px;
            height: 100px;
        }
    </style>
</head>
<body>
    <div class="a">a
        <div class="z">box to</div>
    </div>
    <div class="b">b</div>
    <div class="c">a</div>
    <div class="d">b</div>
    <div class="e">a</div>
    <div class="f">b</div>
</body>
</html>

templates/landingpage.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <title>Landing Page</title>
    <link rel="stylesheet" href="{% static 'css/all.css' %}">
    <link rel="stylesheet" href="{% static 'css/landing.css' %}">
</head>
<body>
    <header>
        <h1><span>D</span>ash<span>P</span>rime</h1>
        <div>
            <a href=""><i class="fa fa-home"></i> Home</a>
            <a href=""><i class="fa fa-comment"></i> Updates</a>
            <a href=""><i class="fa-brands fa-adn"></i> About</a>
            <a href=""><i class="fa-brands fa-hire-a-helper"></i> Help</a>
        </div>
    </header>
    <div id="one">
        <div id="two">
            <h1>Best Company</h1>
            <p>the fact or condition of being with another or others, especially in a way that provides friendship and enjoyment. <br>associate with; keep company with.
               <br> "these men which have companied with us all this time" <br>A company, abbreviated as co., is a legal entity representing an association of people, whether natural, legal or a mixture of both, with a specific objective. Company members share a common purpose and unite to achieve specific, declared goals. Companies take various forms.ect.
            <br><button>Register</button></p>
        </div>
        <a href="{% url 'app3:animation2' %}"><button>animation2</button></a>
        <a href="{% url 'app3:animation3' %}"><button>animation3</button></a>
        <a href="{% url 'app2:login1' %}"><button>login1</button></a>
        <a href="{% url 'app2:login2' %}"><button>login2</button></a>
        <a href="{% url 'app2:login3' %}"><button>login3</button></a>
        <a href="{% url 'app2:card' %}"><button>Card</button></a>
        <a href="{% url 'app1:table' %}"><button>Table</button></a>
        <a href="{% url 'app1:table1' %}"><button>Table1</button></a>
        <a href="{% url 'app1:table2' %}"><button>table2</button></a>
        <a href="{% url 'app1:table3' %}"><button>Table3</button></a>
        <a href="{% url 'app1:table4' %}"><button>Table4</button></a>
        <a href="{% url 'app1:table5' %}"><button>table5</button></a>
    </div>
</body>
</html>

templates/login1.html
<!DOCTYPE html>
<html>
<head>
    <title>LOG IN</title>
    <style>
        div
        {
            background-color: burlywood;
            width: 500px;
            margin: 100px auto;
            border: 5px solid black;
        }
        form
        {
            align-items: center;
            padding: 10px 50px;
            
        }
        h1
        {
            padding: 10px 50px;
        }
    </style>
</head>
<body>
    <div>
        <h1>EDIT YOUR DETAILS</h1>
    <form>
        <table>
        <tr>
            <td><label>Username :</label></td>
            <td><input type="text"></td>
        </tr>
        <tr>
            <td><label>Password :</label></td>
            <td><input type="password"></td>
        </tr>
        <tr>
            <td><label>Full Name :</label></td>
            <td><input type="text"></td>
        </tr>
        <tr>
            <td><label>Emali :</label></td>
            <td><input type="email"></td>
        </tr>
        <tr>
            <td><label>Phone Number :</label></td>
            <td><input type="number"></td>
        </tr>
        <tr>
            <td><label>Address</label></td>
            <td><input type="text"></td>
        </tr>
        <tr>
            <td><label>Hotel Branch</label></td>
            <td><select>
                <option>...SELECT...</option>
                <option>Marthahalli</option>
                <option>Electric City</option>
                <option>White City</option>
            </select></td>
        </tr>
        <tr>
            <td>
                <input type="Submit" value="Update">
                <input type="reset" value="Delete">
            </td>
        </tr>
    </table>
    </form>
    <a href="{% url 'app3:animation2' %}"><button>animation2</button></a>
        <a href="{% url 'app3:animation3' %}"><button>animation3</button></a>
        <a href="{% url 'app1:home' %}"><button>Home</button></a>
        <a href="{% url 'app2:login2' %}"><button>login2</button></a>
        <a href="{% url 'app2:login3' %}"><button>login3</button></a>
        <a href="{% url 'app2:card' %}"><button>Card</button></a>
        <a href="{% url 'app1:table' %}"><button>Table</button></a>
        <a href="{% url 'app1:table1' %}"><button>Table1</button></a>
        <a href="{% url 'app1:table2' %}"><button>table2</button></a>
        <a href="{% url 'app1:table3' %}"><button>Table3</button></a>
        <a href="{% url 'app1:table4' %}"><button>Table4</button></a>
        <a href="{% url 'app1:table5' %}"><button>table5</button></a>
    </div>
</body>
</html>

templates/login3.html
<!DOCTYPE html>
<html>
<head>
    <title>LOG IN 3</title>
    <link rel="stylesheet" href="../CSS/CSS/FONT/css/all.css">
    <style>
        .p
        {
            background-color: azure;
            height: 700px;
            width: 1000px;
            margin-left: 15%;
        }
        .a
        {
            background-color: chocolate;
            padding:30px 0px;
            text-align: center;
        }
        .b
        {
            background-color:rgb(138, 79, 36);
            width: 150px;
            display: inline-block;
            text-align: center;
            padding-top: 13px;
            height: 400px;
            
        }
        a
        {
            display: inline-block;
            margin-bottom: 50px;
            color:blue;
            width:80px;
            text-decoration: none;
        }
        .c
        {
            display: inline-block;
            background-color: rgb(248, 179, 90);
            height:201px;
           /* padding-top: 150px;*/
            width: 825px;
            padding-left: 10px;
            padding-bottom: 213px;
            padding-right: 15px;
            margin-left: -4px;
            position: relative;
            bottom: 150px;
        }
        .d
        {
            background-color: chocolate;
            display:block;
            width:100%;
            left: 0px;
            height: 145px;
            text-align: center;
            position: relative;
            bottom: 151px;

        }
    </style>
</head>
<body>
    <form>
    <div class="p">
        <div class="a">
            <h1>
                JavaJam Coffee House
            </h1>
        </div>
        <div class="b">
            <a href="">Home</a>
            <a href="">Menu</a>
            <a href="">Music</a>
            <a href="">Job</a>
        </div>
        <div class="c">
            <h2>JOb at JavaJam</h2>
            <p>Want to work at JavaJam? Fill out the form below to start your application. Required fields are marked with an asterisk *.</p>
            <table>
                <tr>
                    <th><label>* Name</label></th>
                    <td><input type="text"></td>
                </tr>
                <tr>
                    <th><label>* E-mail </label></th>
                    <td><input type="mail"></td>
                </tr>
                <tr>
                    <th><label>Start Date</label></th>
                    <td><input type="date"></td>
                </tr>
                <tr>
                    <th><label>Experience</label></th>
                    <td><textarea cols="16" rows="2"></textarea></td>
                </tr>
                <tr>
                    <td><input type="submit" value="Enquiry Complete"></td>
                </tr>
            </table>
        </div>
        <div class="d">
            <br><br> copyright <i class="fa fa-copyright"></i>2016 JavaJam Coffee House <br>
            <a href="">JavaJam.com</a>
        </div>
    </div>
    </form>
</body>
</html>

templates/table.html
<!DOCTYPE html>
<html>
<head>
       <title>Table1</title>
</head>
<body>
    <table border="2px" align="center">
        <tr>
            <th rowspan="2"></th>
            <th colspan="2">AVERAGE</th>
            <th rowspan="2"> RED EYES</th>
        </tr>
        <tr>
            <th>HEIGHT</th>
            <th>WEIGHT</th>
        </tr>
        <tr>
            <th>MALES</th>
            <td>1.9</td>
            <td>0.003</td>
            <td>40%</td>
        </tr>
        <tr>
            <th>FEAMALES</th>
            <td>1.7</td>
            <td>0.002</td>
            <td>43%</td>
        </tr>
    </table>
    <a href="{% url 'app1:home' %}"><button>Home</button></a>
    <a href="{% url 'app3:animation2' %}"><button>animation2</button></a>
    <a href="{% url 'app3:animation3' %}"><button>animation3</button></a>
    <a href="{% url 'app2:login1' %}"><button>login1</button></a>
    <a href="{% url 'app1:home' %}"><button>Home</button></a>
    <a href="{% url 'app2:login3' %}"><button>login3</button></a>
    <a href="{% url 'app1:table' %}"><button>Table</button></a>
    <a href="{% url 'app1:table1' %}"><button>Table1</button></a>
    <a href="{% url 'app1:table2' %}"><button>table2</button></a>
    <a href="{% url 'app1:table3' %}"><button>Table3</button></a>
    <a href="{% url 'app1:table4' %}"><button>Table4</button></a>
    <a href="{% url 'app1:table5' %}"><button>table5</button></a>
</body>
</html>

templates/table2.html
<!DOCTYPE html>
<html>
<head>
    <title>TABLE 2</title>
</head>
<body>
    <table border="5px" cellspacing="4px" cellpadding="10px">
        <tr>
            <th rowspan="2">HEADING</th>
            <th>STUDENTS</th>
            <th colspan="3"> DETAILS</th>    
        </tr>
        <tr>
            <th>ID</th>
            <th>NAME</th>
            <th>DEPARTMENT</th>
            <th>ROLL NUMBER</th>
        </tr>
        <tr>
            <td rowspan="4"> Student List</td>
            <td>1</td>
            <td>Victor</td>
            <td>Computer Science</td>
            <td>12345</td>
        </tr>
        <tr>
            <td>2</td>
            <td>Williams</td>
            <td>Electronics</td>
            <td>23456</td>
        </tr>
        <tr>
            <td>3</td>
            <td>Harry</td>
            <td>Electrical</td>
            <td>34567</td>
        </tr>
        <tr>
            <td>4</td>
            <td>Rick</td>
            <td>Civil</td>
            <td>45678</td>
        </tr>
    </table>
    <a href="{% url 'app1:home' %}"><button>Home</button></a>
    <a href="{% url 'app3:animation2' %}"><button>animation2</button></a>
    <a href="{% url 'app3:animation3' %}"><button>animation3</button></a>
    <a href="{% url 'app2:login1' %}"><button>login1</button></a>
    <a href="{% url 'app1:home' %}"><button>Home</button></a>
    <a href="{% url 'app2:login3' %}"><button>login3</button></a>
    <a href="{% url 'app1:table' %}"><button>Table</button></a>
    <a href="{% url 'app1:table1' %}"><button>Table1</button></a>
    <a href="{% url 'app1:table2' %}"><button>table2</button></a>
    <a href="{% url 'app1:table3' %}"><button>Table3</button></a>
    <a href="{% url 'app1:table4' %}"><button>Table4</button></a>
    <a href="{% url 'app1:table5' %}"><button>table5</button></a>
</body>
</html>

templates/table3.html
<!DOCTYPE html>
<html >
<head>
    <title>TABLE 3</title>
</head>
<body>
    <table border="4px" cellspacing="4px" cellpadding="5px">
    <tr>
        <th>Day/Period</th>
        <th>I <br>9:30 - 10:20</th>
        <th>II <br>10:20 - 11:10</th>
        <th>III <br>11:10 - 12:00</th>
        <th>12:00 - 12:40</th>
        <th>IV <br>12:40 - 1:30</th>
        <th>V <br>1:30 - 2:20</th>
        <th>VI <br>2:20 - 3:10</th>
        <th>VII <br>3:10 - 4:00</th>
    </tr>
    <tr>
        <th>Monday</th>
        <td>Eng</td>
        <td>Mat</td>
        <td>che</td>
        <th rowspan="6">L <br>U <br>N <br>C <br>H</th>
        <td colspan="3">Lab</td>
        <td>Play</td>
    </tr>
    <tr>
        <th>Tuesday</th>
        <td colspan="3">Lab</td>
        <td>Eng</td>
        <td>che</td>
        <td>Mat</td>
        <td>Sport</td>
    </tr>
    <tr>
        <th>Wedensday</th>
        <td>Mat</td>
        <td>Play</td>
        <td>Eng</td>
        <td>Che</td>
        <td colspan="3">LIBRARY</td>
    </tr>
    <tr>
        <th>Thursday</th>
        <td>Play</td>
        <td>Eng</td>
        <td>che</tds>
        <td colspan="3">Lab</td>
        <td>Mat</td>
    </tr>
    <tr>
        <th>Friday</th>
        <td colspan="3">Lab</td>
        <td>Mat</td>
        <td>Che</td>
        <td>Eng</td>
        <td>Play</td>
    </tr>
    <tr>
        <th>Saturday</th>
        <td>Eng</td>
        <td>Che</td>
        <td>Mat</td>
        <td colspan="3">SEMINAR</td>
        <td>Sport</td>
    </tr>
    </table>
    <a href="{% url 'app1:home' %}"><button>Home</button></a>
    <a href="{% url 'app3:animation2' %}"><button>animation2</button></a>
    <a href="{% url 'app3:animation3' %}"><button>animation3</button></a>
    <a href="{% url 'app2:login1' %}"><button>login1</button></a>
    <a href="{% url 'app1:home' %}"><button>Home</button></a>
    <a href="{% url 'app2:login3' %}"><button>login3</button></a>
    <a href="{% url 'app1:table' %}"><button>Table</button></a>
    <a href="{% url 'app1:table1' %}"><button>Table1</button></a>
    <a href="{% url 'app1:table2' %}"><button>table2</button></a>
    <a href="{% url 'app1:table3' %}"><button>Table3</button></a>
    <a href="{% url 'app1:table4' %}"><button>Table4</button></a>
    <a href="{% url 'app1:table5' %}"><button>table5</button></a>
</body>
</html>

templates/table5.html
<!DOCTYPE html>
<html>
<head>
    <title>TABLE 5</title>
</head>
<body>
    <table border="5px" cellspacing="5px" cellpadding="5px">
        <tr>
            <th rowspan="3">DAY</th>
            <th colspan="3">SEMINAR</th>
        </tr>
        <tr>
            <th colspan="2">SCHEDULE</th>
            <th rowspan="2">TOPIC</th>
        </tr>
        <tr>
            <th>BEGIN</th>
            <th>END</th>
        </tr>
        <tr>
            <td rowspan="2">MONDAY</td>
            <td rowspan="2">8:00 a.m.</td>
            <td rowspan="2">5:00 p.m.</td>
            <td>Introduction to XML</td>
        </tr>
        <tr>
            <td>Validity : DTD and Relax NG</td>
        </tr>
        <tr>
            <td rowspan="3">TUESDAY</td>
            <td>8:00 a.m.</td>
            <td>11:00 a.m.</td>
            <td rowspan="2">XPath</td>
        </tr>
        <tr>
            <td>11:00 a.m.</td>
            <td>2:00 p.m.</td>
        </tr>
        <tr>
            <td>2:00 p.m.</td>
            <td>5:00 p.m.</td>
            <td>XSL Transformation</td>
        </tr>
        <tr>
            <td>WEDENSDAY</td>
            <td>8:00 a.m.</td>
            <td>12:00 p.m.</td>
            <td>XSL Formating Objects</td>
        </tr>
    </table>
    <a href="{% url 'app1:home' %}"><button>Home</button></a>
    <a href="{% url 'app3:animation2' %}"><button>animation2</button></a>
    <a href="{% url 'app3:animation3' %}"><button>animation3</button></a>
    <a href="{% url 'app2:login1' %}"><button>login1</button></a>
    <a href="{% url 'app1:home' %}"><button>Home</button></a>
    <a href="{% url 'app2:login3' %}"><button>login3</button></a>
    <a href="{% url 'app1:table' %}"><button>Table</button></a>
    <a href="{% url 'app1:table1' %}"><button>Table1</button></a>
    <a href="{% url 'app1:table2' %}"><button>table2</button></a>
    <a href="{% url 'app1:table3' %}"><button>Table3</button></a>
    <a href="{% url 'app1:table4' %}"><button>Table4</button></a>
    <a href="{% url 'app1:table5' %}"><button>table5</button></a>
</body>
</html>

templates/textformating tag.html
<!DOCTYPE html>
<html> 
<head>
    <title>Document</title>
</head>
<body>
    <p>nsnfnosvjvjnvjjvjvnjihhinjjnigfihihhvinjnjv</p>
    <hr>
    <b>khamdale</b>
    <strong>dashrath MORE348</strong>
    <hr>
    <u>u == hi love janu</u>
    <ins>ins == knkvnvnvjnkvnnkvnkvnvnnvnvnn</ins>
    <hr>
    <s>s == knkvnvnvjnkvnnkvnkvnvnnvnvnn</s> <br>
    <strike>strike == knkvnvnvjnkvnnkvnkvnvnnvnvnn</strike>
    <hr>
    <del> del == knkvnvnvj</del>
    <hr>
    <mark>mark == knkvnvnvjnkvnnkvnkvnvnnvnvnn</mark>
    <hr>
    <address>address == h.no=64, <mark> AT. Khamdale,</mark> po.=here, tal.= chandgad, dist.= kolhapur</address>
    <hr>
    <code>code == knkv 1234 sddsds</code>
    <hr> */formula/*
    <sub>sub == knkvnvnvjnkvnnkvnkvnvnnvnvnn</sub> <br> H <sub>2</sub>O <br>
    <sup>sup == knkvnvnvjnkvnnkvnkvnvnnvnvnn</sup> <br> 2 <sup>2</sup>
    <hr>
    <span> span == knkvnvnvjnkvnnkvnkvnvnnvnvnn</span>
    <hr>
    <i>i == knkvnvnvjnkvnnkvnkvnvnnvnvnn</i>
    <em>em == knkvnvnvjnkvnnkvnkvnvnnvnvnn</em>
    <hr>
    <ins>ins == DASHRATH janewary more12132342</ins>
    <hr>
    <pre> */ for same textline /*
        for i in range(0,9):
            print(i)
    </pre>
</body>
</html>

templates/translate.html
<!DOCTYPE html>
<html>
<head>
    <title>Translate</title>
    <style>
        div
        {
            box-shadow: 0px 0px 5px black;
            width: 400px;
            height: 400px;
            margin: 100px auto;
            overflow: hidden;
            position: relative;
        }
        div>img
        {
            width: inherit;
            height: inherit;
            transition: all 1s linear 0s;
        }
        div:hover>img
        {
            transform: translateY(-100px);
        }
        div>#b
        {
            position: absolute;
            background-color: black;
            color: aliceblue;
            top:300px;
            transition: all 1s linear 0s;
            text-align: center;

        }
        div:hover>#b
        {
            transform: translateY(-100px);
        }
    </style>
</head>
<body>
    <div>
        <img src="../PIC/shirt.jpg" alt="">
        <div id="b">
            <ol>
                <p>RED SHIRT <br>
                price : 500</p>
            </ol>
        </div>
    </div>
</body>
</html>